# Generated by Django 4.2.3 on 2023-07-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rbac_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="token",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="userapiaccess",
            name="tokens",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
