# Generated by Django 4.2.3 on 2023-07-28 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rbac_app", "0003_rename_token_customuser_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="api",
            name="user_id",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
